sudo: false
language: node_js
node_js:
  - 'node'
  - '9'
before_install:
  - cd 04-configure-jest-for-javascript-applications/
install: npm install
script: npm test
after_script: npx codecov@3
branches:
  only: master
